name: DISTRO Core Scheduler Keepalive

description: >-
  Action to keep workflow scheduler alive. Adapted from
  liskin/gh-actions-keepalive.

branding:
  icon: activity
  color: red

########################################################################

inputs:
  GITHUB_TOKEN:
    required: false
    description: >-
      GITHUB_TOKEN with actions: write permissions
      (default: github.token)

########################################################################

runs:
  using: composite
  steps:

  - name: Environment
    id: environment
    shell: bash
    run: |
      : environment based on runtime

  - name: Install GitHub Hosted
    id: install-github-hosted
    if: runner.environment == 'github-hosted'
    shell: bash
    run: |
      : install github-hosted

  - name: Install Self Hosted
    id: install-self-hosted
    if: runner.environment == 'self-hosted'
    shell: bash
    run: |
      : install self-hosted

  - name: Configure
    id: configure
    shell: bash
    run: |
      : configure

  - name: Execute
    id: execute
    env:
      GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN || github.token }}
    shell: sh
    run: |
      : keep-alive
      case "${GITHUB_WORKFLOW_REF:?}" in
        "${GITHUB_REPOSITORY:?}"/.github/workflows/*.y*ml@*) ;;
        *) false ;;
      esac
      workflow="${GITHUB_WORKFLOW_REF%%@*}"
      workflow="${workflow#${GITHUB_REPOSITORY}/.github/workflows/}"
      gh api -X PUT "repos/${GITHUB_REPOSITORY}/actions/workflows/${workflow}/enable"

  - name: Generate Outputs
    id: gen-outputs
    shell: bash
    run: |
      : generate outputs

  - name: Generate Summary
    id: gen-summary
    shell: bash
    run: |
      : generate summary
