# SPDX-License-Identifier: MIT

name: DISTRO Core Context Diagnostic
description: >-
  Action to perform a context dump.

branding:
  icon: activity
  color: red

########################################################################

runs:
  using: composite
  steps:

  - name: Environment
    id: environment
    shell: bash
    run: |
      : environment based on runtime

  - name: Install GitHub Hosted
    id: install-github-hosted
    if: runner.environment == 'github-hosted'
    shell: bash
    run: |
      : install github-hosted

  - name: Install Self Hosted
    id: install-self-hosted
    if: runner.environment == 'self-hosted'
    shell: bash
    run: |
      : install self-hosted

  - name: Configure
    id: configure
    shell: bash
    run: |
      : configure

  - name: Execute
    id: execute
    shell: bash
    run: |
      : execute

  - name: Generate Outputs
    id: gen-outputs
    shell: bash
    run: |
      : generate outputs

  - name: Generate Summary
    id: gen-summary
    shell: bash
    env:
      CONTEXT_GITHUB: ${{ toJson(github) }}
      CONTEXT_RUNNER: ${{ toJson(runner) }}
      CONTEXT_ENV: ${{ toJson(env) }}
      CONTEXT_JOB: ${{ toJson(job) }}
      CONTEXT_INPUTS: ${{ toJson(inputs) }}
    run: |
      : generate summary
      cat <<EOF # >>$GITHUB_STEP_SUMMARY
      #### Context Diagnostic
      CONTEXT: github
      ~~~ json
      $CONTEXT_GITHUB
      ~~~
      CONTEXT: runner
      ~~~ json
      $CONTEXT_RUNNER
      ~~~
      EOF
